### ISSUE TITLE
Problem in Basemap

### ISSUE THREAD

**Issue by dharanidharan12** [knutfrode/opendrift#17]
Sorry for Troubling you,
I just want to create a base map for Chennai Coast. but, I don't know how to create the basemap.
Please help me to create the map for Chennai Coast.

Thanks in Advance!!!

**Comment by knutfrode** [comment]
Hi,

A basemap reader can be created like this by giving the lon and lat values of the lower left corner ("llcrnr") and upper right corner ("urcrnr"):

>>> from readers import reader_basemap_landmask
>>> reader_basemap = reader_basemap_landmask.Reader(
                    llcrnrlon=79.7, llcrnrlat=12.6,
                    urcrnrlon=81.0, urcrnrlat=13.8,
                    resolution='f', projection='merc')

Resolution 'f' ('full') is the finest, and may take a few seconds to generate. For more information about the parameters, see the original Basemap documentation:
http://matplotlib.org/basemap/api/basemap_api.html
Also I recommend to study the example-python-scripts bundled with OpenDrift

Best regards from Knut-Frode

**Comment by dharanidharan12** [comment]
Thanks!! now working on it.
But ,how to create the netcdf file for the basemap

**Comment by knutfrode** [comment]
I am not sure what you mean by "creating the netcdf file"?

The created "basemap reader" is a Reader-object which can provide a
coastline for an opendrift simulation:
https://github.com/knutfrode/opendrift/wiki/How-to-run-a-trajectory-simulation



2016-08-09 15:00 GMT+02:00 Dharani_Dharan <notifications@github.com>:

**Comment by dharanidharan12** [comment]
how to save the animation image in a directory.
here a=object
while using 
a.plot()   I am getting the plotted image
a.animation()  I am getting the animation image in gif format
But don't know to save the (animated image ) gif image  (in a specific path).  

 And  how to control the oil flow, while running the code it's just like spraying the oil, at a fast rate. how to slow down the flow of oil.

**Comment by trondkr** [comment]
Just use the optional argument 'filename'. E.g:

plotFilename='figures/myplot.gif'
o.plot(linecolor='z',filename=plotFilename)

Will save the plot to the existing local folder 'figures' under the name 'myplot.gif'

**Comment by dharanidharan12** [comment]
I changed it , but it's not working for me..
What I did wrong

**Comment by knutfrode** [comment]
If 'gif' does not work, you can try with '.png' for plot() and '.mp4' for animation()

For mp4-animation you might need to install FFMPEG library, as discussed in this section:
https://github.com/knutfrode/opendrift/wiki/How-to-run-a-trajectory-simulation#6-plotting-and-analysing-the-results

**Comment by dharanidharan12** [comment]
how to create current and wind for my location. 
In Default code it's work's fine.
once I updated with my latitude and longitude the wind and current doesn't takes effect.
While using **o.animation()**   it just spreading in all directions.   There is no flow related to the current and wind..
Thanks in Advance!!

**Comment by johannesro** [comment]
You have to implement an ocean model to create current for your location. This is not done in opendrift, but with separate models.

For example, use ROMS:
http://www.myroms.org/

or download current data from existing ocean models, i.e.
https://hycom.org/dataserver/glb-analysis

You will need to read up on how to use these tools and datasets.

**Comment by dharanidharan12** [comment]
How to create  types of oils in opendrift,  like as in NOAA.


Thanks in Advance!!!

**Comment by dharanidharan12** [comment]
local variable 'io_module' referenced before assignment
error:
models/opendrift.py in __init__, line 187

what i did wrong ... 

While migrating the code with the pythonpath.

please help.
thanks in advance!!!

**Comment by knutfrode** [comment]
It is hard to say what causes this error without more information about
which commands you have executed, how you set your PATH, etc.

However, it could happen that your folder got messy after the recent
structure changes of OpenDrift.
I recommend that you delete your whole opendrift-folder, and download and
install from scratch, as explained here:
https://github.com/knutfrode/opendrift/wiki#download-and-installation

Then you can check that everything  works by running the testall-script,
and the example-scripts.

2016-09-01 10:12 GMT+02:00 Dharani_Dharan <notifications@github.com>:

**Comment by dharanidharan12** [comment]
how to use different kinds of oils such as gasoline, kerosene, crudeoil

**Comment by knutfrode** [comment]
OpenDrift has hitherto focussed mainly on the transport (horisontal and
vertical) due to various forcing (typical current, wind and waves)
Oil weathering is presently very primitive, and basically "density" is the
only parameter you can set when seeding (see e.g.
example_oil3d_verticalmixing.py).
More proper oil weathering will be added to OpenOil and OpenOil3D within
the coming months.

For more sophisticated treatment of oil weathering, the NOAA PyGnome model
is recommended:
https://github.com/NOAA-ORR-ERD/PyGnome


2016-09-01 11:01 GMT+02:00 Dharani_Dharan <notifications@github.com>:

**Comment by johannesro** [comment]
delete your opendrift code and download it again in a new directory, that
will solve the problem.

Johannes Röhrs, PhD
Norwegian Meteorological Institute
www.met.no / www.yr.no

johannes.rohrs@met.no
+47 41654886

**Comment by dharanidharan12** [comment]
Issue Solved...
**Thanks I solved the io_module error.**

> the export folder is not related properly. so the io_netcdf.py is not read.

**Now I fixed the issue.**

Thanks !!!

**Comment by dharanidharan12** [comment]
how to get image for every 3hours..
using  

> o.run()

I need to get image and save the image for every 3 hours. 
Please help!!!
Thanks in Advance!!!
