### ISSUE TITLE
Seafloor condition in OceanDrift

### ISSUE THREAD

**Issue by msdelalama** [knutfrode/opendrift#24]
Hi,

Some days ago I included in OceanDrift the seafloor condition (as it is implemented in openoil):

---------------------------------------------------------------------------------------
 if hasattr(self.environment, 'sea_floor_depth_below_sea_level'):
            self.elements.z[np.where(
                self.elements.z <
                -self.environment.sea_floor_depth_below_sea_level)] = \
                -self.environment.sea_floor_depth_below_sea_level

---------------------------------------------------------------------------------------
It was working well. But now the drifters again cross the seafloor boundary, and I don't understand why (I am working with a copy of the master branch and ROMS_native reader). Has anything changed that I am not aware of in the master branch?

If I directly check hasattr(o.environment, 'sea_floor_depth_below_sea_level') I get it false, but the 
sea_floor_depth appears as a variable if I check o.readers (output below): 

---------------------------------------------------------------------------------------
, 'roms native_0': ===========================
Reader: roms native_0
Projection: 
  None
Coverage: [pixels]
  xmin: 0.000000   xmax: 1201.000000   step: 1   numx: 1202
  ymin: 0.000000   ymax: 579.000000   step: 1   numy: 580
  Corners (lon, lat):
    (-28.67,  52.74)  (132.13,  81.81)
    (  0.58,  46.46)  ( 75.76,  64.55)
Vertical levels [sigma]: 
  [-0.984375 -0.953125 -0.921875 -0.890625 -0.859375 -0.828125 -0.796875
 -0.765625 -0.734375 -0.703125 -0.671875 -0.640625 -0.609375 -0.578125
 -0.546875 -0.515625 -0.484375 -0.453125 -0.421875 -0.390625 -0.359375
 -0.328125 -0.296875 -0.265625 -0.234375 -0.203125 -0.171875 -0.140625
 -0.109375 -0.078125 -0.046875 -0.015625]
Available time range:
  start: 2013-02-01 12:00:00   end: 2013-02-28 12:00:00   step: 1 day, 0:00:00
    28 times (0 missing)
Variables:
  sea_floor_depth_below_sea_level
  land_binary_mask
  x_sea_water_velocity
  y_sea_water_velocity

---------------------------------------------------------------------------------------

Thanks in advance!

Marta.

**Comment by knutfrode** [comment]
A bug related to name of "sea_floor_depth" (discovered by Kristina Øie Kvile) was fixed one month ago, but I believe you have updated your repository after that?
https://github.com/knutfrode/opendrift/commit/b445715ff0caedae20e99116b732a3f3760b2295

In any case, a major restructuring was done two weeks ago, where OpenDrift is now on "standard package form". Apparently some deleted files might seem to remain after a normal "git pull", so I would recommend deleting your whole opendrift folder (after backing up eventual local modifications), and then check out and install again as explained in the wiki:
https://github.com/knutfrode/opendrift/wiki#download-and-installation

If you still get the same error, I will have a closer look at it. It could then help if you send the last hundred lines or so of your debug-output (loglevel=0).
Anyway, I think I should generalise this functionality and make it available for any sub-modules, or perhaps doing it automatically.
