### ISSUE TITLE
sequential seeding of particles (example_grid_time.py)

### ISSUE THREAD

**Issue by msdelalama** [knutfrode/opendrift#26]
Hi,
It seems to be a problem with the output-writing routine when doing sequential deployments of particles. I have checked that one gets it also when using the example_grid_time.py from the examples folder.
The run goes well and one can see very nice trajectories of the particles with o.animation().
However, when trying to write the output into a file the writing routine seems to have a problem: 

----------------------------------------------------------------------------------------------

start_time = reader_norkyst.start_time
time_step = timedelta(hours=6)
num_steps = 10
for i in range(num_steps+1):
    o.seed_elements(lons, lats, radius=0, number=100,
                    time=start_time + i*time_step)
o.run(steps=66*4, time_step=900,outfile='test.nc')

-----------------------------------------------------------------------------------------------

Only the trajectories of particles deployed at the initial time are properly saved. Starting from particle 100, the output I got (ie, for the records lon,lat,z,age,..in the file test.nc ) has nonsense (at least at first glance!).
Any idea?
Thanks in advance!

Marta.

**Comment by knutfrode** [comment]
Hi,

Could you please post a complete script reproducing this error? Ideally using the current-data included in the repository, and ideally also with as few particles and timesteps as possible.

If simply modifying example_grid_time.py to export to file, I am not able to reproduce the problem. However, this could be related to different netCDF versions, and whether undefined values are masked (as they should) or not.

Knut-Frode

**Comment by msdelalama** [comment]
Then is probably due to different netCDF versions, because I simply added the command to export to file in example_grid_time.py.
I add a copy of the modified script and also of the output I get when running "python setup.py develop --user", to visualize the versions I am using.
Thanks!

[example_grid_time.txt](https://github.com/knutfrode/opendrift/files/469861/example_grid_time.txt)

[setup_output.txt](https://github.com/knutfrode/opendrift/files/469856/setup_output.txt)

**Comment by knutfrode** [comment]
Are you able to import the saved file with OpenDrift?

o = OceanDrift()
o.io_import_file('test.nc')
o.animation()
o.plot()

The full data history is available in the numpy array o.history, which
should contain masked values (and not garbage values like 9e+36) for
unseeded and deactivated elements.


2016-09-13 15:07 GMT+02:00 Marta S. de La Lama <notifications@github.com>:

**Comment by msdelalama** [comment]
This is exactly what is recorded in the output file, garbage values like 9e+36 for drifters that are not supposed to be stranded or deactivated.
The import function does not work. This is what I get when calling it (but animation() and plot() work well):

------------------------------------------------------------

>>> o.io_import_file('./test_example_grid_time.nc')
OceanDrift does not contain trajectory - skipping.
OceanDrift does not contain time - skipping.
OceanDrift does not contain x_wind - skipping.
OceanDrift does not contain y_sea_water_velocity - skipping.
OceanDrift does not contain y_wind - skipping.
OceanDrift does not contain land_binary_mask - skipping.
OceanDrift does not contain x_sea_water_velocity - skipping.
DEBUG: Removed 44 elements.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/net/vann/mn/vann/metos-d5/martsanc/ROMS_offline/OPENDRIFT_git/opendrift/opendrift/export/io_netcdf.py", line 205, in import_file
    self.remove_deactivated_elements()
  File "/net/vann/mn/vann/metos-d5/martsanc/ROMS_offline/OPENDRIFT_git/opendrift/opendrift/models/basemodel.py", line 906, in remove_deactivated_elements
    self.environment = self.environment[~indices]
  File "/opt/uio/modules/packages/python/Anaconda2/lib/python2.7/site-packages/numpy/core/records.py", line 499, in __getitem__
    obj = super(recarray, self).__getitem__(indx)
IndexError: index 1056 is out of bounds for axis 1 with size 1056

**Comment by knutfrode** [comment]
Turned out to be a problem with Matlab post-processing script, where masks were not automatically applied when importing from netCDF.
