### ISSUE TITLE
reader error

### ISSUE THREAD

**Issue by dharanidharan12** [knutfrode/opendrift#28]
While running the code as a file it's working fine. 
But implementing the code within the python function , it showing this error
**Please provide Reader object**

What I have to do for this kind of error.
Please help!!!
Thanks in Advance!!!

**Comment by knutfrode** [comment]
What do you mean by "implementing the code within the python function"?
Can you please post the commands (full history) which lead to the error?

2016-10-19 14:19 GMT+02:00 Dharani_Dharan <notifications@github.com>:

**Comment by dharanidharan12** [comment]
sorry I did the mistake cant specify the path  .  Now Its working.   Sorry sir
