### ISSUE TITLE
Animation of part of the domain?

### ISSUE THREAD

**Issue by AndresSepulveda** [knutfrode/opendrift#30]
Hi,
I am running OpenDrift (using OceanDrift) for a large domain, but I would like to save the animation for a smaller area of it. How can define this window?   (o.animation)

Would it apply for the final plot also? (o.plot)

**Comment by knutfrode** [comment]
Hi Andres,
For economical reasons (it takes time to generate a Basemap), OpenDrift normally re-uses the map/reader which has been used to check stranding also for the plotting. If this has been deleted from the dictionary ```o.readers```, or after importing from a netCDF-file, a new Basemap will be automatically generated, tightly encompassing the data.

Unfortunately I have found no good way to zoom in on an existing Basemap instance, but a workaround is to delete the existing Basemap, and generate and add a custom one:
```
del o.readers['basemap_landmask']
reader_basemap = reader_basemap_landmask.Reader(
    llcrnrlon=4.6, llcrnrlat=59.9,
    urcrnrlon=5.1, urcrnrlat=60.2,
    resolution='h', projection='merc')
o.add_reader(reader_basemap)
```
This new Basemap will be used for subsequent plots and animations.

**Comment by AndresSepulveda** [comment]
That works fine, thanks!
