### ISSUE TITLE
Reading of curvilinear grids

### ISSUE THREAD

**Issue by knutfrode** [knutfrode/opendrift#7]
e.g. ROMS Oslofjord

**Comment by knutfrode** [comment]
Work is ongoing for native ROMS format.

**Comment by nilsmkMET** [comment]
Is there maybe a bug in the ROMS_native-reader?
I have to change this: `self.times = num2date(ocean_time, time_units)` to this `self.times = num2date(ocean_time[:], time_units)` to make the code work. The native ROMS-data is read from a thredds-server.

**Comment by knutfrode** [comment]
I have never tested with sigma-files from Thredds, but your suggested change works also for local files, so I now committed your modification to master. Indeed, it is strange that it worked for local files since ocean_time is a variable object and not an array...

Note that I have not yet implemented vertical interpolation for sigma0-coordinates; planning to do that early next week.

**Comment by knutfrode** [comment]
The reader_ROMS_native reader reades curvilinear grids, and rotates vectors according to angle matrix read from the file. 3D blocks are regridded from sigma to z-coordinates using roppy package of Bjørn Aadlandsvik.
