### ISSUE TITLE
Problem With Animation 

### ISSUE THREAD

**Issue by RicardoCastilloVega** [knutfrode/opendrift#9]
Dear Knut
I'm new in OpenDrift and python and I have a problem with animation of examples, when I run the models no show the animation only the plot and  display following:
===========================
INFO: Saving animation to openoil_time_seed.gif...

Could not save animation:INFO: save() got an unexpected keyword argument 'clear_temp'
DEBUG: Traceback (most recent call last):
  File "models\opendrift.py", line 1006, in animation
    anim.save(filename, fps=20, clear_temp=False)
TypeError: save() got an unexpected keyword argument 'clear_temp'

 I'm Using python(x,y) and the file that I ran was "example.py"

regards
Ricardo

**Comment by knutfrode** [comment]
Dear Ricardo,

It seems you have a different (probably newer) version of Matplotlib than myself.
Can you remove the clear_temp-parameter from that line in /models/opendrift.py to:

anim.save(filename, fps=20)

and see if that works?
Can you also please tell me your matplotlib version (import matplotlib; print matplotlib.__version__) - then I can update the code to support both the older and newer versions.

Best regards from Knut-Frode

**Comment by RicardoCastilloVega** [comment]
Dear Knut
Thank for your prompt response. Now I installed Enthought Canopy Academic distribution and   shows the animation,  but don't save it . I remove clear_temp-parameter  but don't works, Despite to erase it, continues the same error: 

INFO: Deleting temporary figures...
INFO: Saving animation to openoil_time_seed.gif...

Could not save animation:INFO: save() got an unexpected keyword argument 'clear_temp'
DEBUG: Traceback (most recent call last):
  File "C:\Users\RicardoAlfonso\Desktop\Practica\OpenDrift\opendrift-master\models\opendrift.py", line 1006, in animation
    anim.save(filename, fps=20)
TypeError: save() got an unexpected keyword argument 'clear_temp'

The matplotlib version is 1.4.3 

Saludos Cordiales 
Ricardo

**Comment by knutfrode** [comment]
I suspect you have an old .pyc-file (opendrift.pyc) in the same folder, which is executed instead of the .py-file you updated. Can you please delete opendrift.pyc (if it exists), then restart python and try again?

**Comment by knutfrode** [comment]
The 'clear_temp' parameter is removed in 1cb967ec5f8efecccfc40437d69737ccd273f7b5 for compatibility with newer versions of Matplotlib.
